		<script type="text/javascript" src="{{ asset('assets/plugins/jquery-validation/dist/jquery.validate.min.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/jquery-validation/dist/additional-methods.min.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/fuelux/js/spinner.min.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/ckeditor/ckeditor.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/select2/select2.min.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/clockface/js/clockface.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/bootstrap-daterangepicker/moment.min.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/jquery.input-ip-address-control-1.0.min.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/jquery-multi-select/js/jquery.multi-select.js') }}"></script>
		<script type="text/javascript" src="{{ asset('assets/plugins/jquery-multi-select/js/jquery.quicksearch.js') }}"></script>
		<script src="{{ asset('assets/plugins/jquery.pwstrength.bootstrap/src/pwstrength.js') }}" type="text/javascript"></script>
		<script src="{{ asset('assets/plugins/bootstrap-switch/static/js/bootstrap-switch.min.js') }}" type="text/javascript"></script>
		<script src="{{ asset('assets/plugins/jquery-tags-input/jquery.tagsinput.min.js') }}" type="text/javascript"></script>
		<script src="{{ asset('assets/plugins/bootstrap-markdown/js/bootstrap-markdown.js') }}" type="text/javascript"></script>
		<script src="{{ asset('assets/plugins/bootstrap-markdown/lib/markdown.js') }}" type="text/javascript"></script>
		<script src="{{ asset('assets/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js') }}" type="text/javascript"></script>
		<script src="{{ asset('assets/plugins/bootstrap-touchspin/bootstrap.touchspin.js') }}" type="text/javascript"></script>